(()=>{const KEY="kr-next-api-url";let frame=null,bridgeReady=false,readyResolve=null,readyPromise=null;const pending=new Map();
function apiUrl(){return localStorage.getItem(KEY)||""}
function bridgeUrl(){const u=apiUrl();if(!u)return"";try{const x=new URL(u);x.searchParams.set("action","bridge");return x.toString()}catch{return""}}
function resetBridge(){bridgeReady=false;if(frame){frame.remove();frame=null}readyPromise=null;readyResolve=null}
function initBridge(){resetBridge();const url=bridgeUrl();if(!url)return;readyPromise=new Promise(ok=>readyResolve=ok);frame=document.createElement("iframe");frame.setAttribute("aria-hidden","true");frame.style.cssText="position:fixed;width:1px;height:1px;left:-9999px;top:-9999px;border:0";frame.src=url+(url.includes("?")?"&":"?")+"_="+Date.now();document.body.appendChild(frame)}
function setApiUrl(v){v=String(v||"").trim();if(v)localStorage.setItem(KEY,v);else localStorage.removeItem(KEY);initBridge();updateStatus();return v}
function makeId(op,entityId){return op+":"+entityId+":"+Date.now()+":"+Math.random().toString(36).slice(2,8)}
function wait(ms){return new Promise((_,ng)=>setTimeout(()=>ng(new Error("BRIDGE_TIMEOUT")),ms))}
async function requestBridge(request,payload,timeout=5000){if(!apiUrl())throw new Error("GREEN_API_NOT_CONFIGURED");if(!frame)initBridge();if(!bridgeReady){if(!readyPromise)throw new Error("BRIDGE_NOT_READY");await Promise.race([readyPromise,wait(timeout)])}const requestId="gbr-"+Date.now()+"-"+Math.random().toString(36).slice(2,8);return new Promise((ok,ng)=>{const timer=setTimeout(()=>{pending.delete(requestId);ng(new Error("BRIDGE_RESPONSE_TIMEOUT"))},timeout);pending.set(requestId,{ok,ng,timer});frame.contentWindow.postMessage({type:"kr-next-green-request",requestId,request,payload:payload||{}},"*")})}
window.addEventListener("message",e=>{const d=e.data||{};if(d.type==="kr-next-green-bridge-ready"){bridgeReady=true;readyResolve&&readyResolve(true);updateStatus();return}if(d.type==="kr-next-green-response"&&d.requestId){const p=pending.get(d.requestId);if(!p)return;clearTimeout(p.timer);pending.delete(d.requestId);d.error?p.ng(new Error(d.error)):p.ok(d.result)}});

async function enqueue(op,entityId,payload){const job={id:makeId(op,entityId),operation:op,entityId,payload,status:"pending",attempts:0,createdAt:new Date().toISOString()};await KRDB.enqueue(job);updateStatus();return job}
async function fetchPost(job){const url=apiUrl();const r=await fetch(url,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({source:"kaitori-rescue-next",idempotencyKey:job.id,operation:job.operation,entityId:job.entityId,payload:job.payload})});if(!r.ok)throw new Error("HTTP_"+r.status);const t=await r.text();let d={};try{d=JSON.parse(t)}catch{d={ok:true,text:t}}if(d.ok===false)throw new Error(d.error||"API_ERROR");return d}
async function post(job){if(!apiUrl())throw new Error("GREEN_API_NOT_CONFIGURED");try{return await requestBridge("write",{job},5000)}catch(e){return await fetchPost(job)}}
async function run(op,entityId,payload){const job=await enqueue(op,entityId,payload);if(!apiUrl()||!navigator.onLine)return{queued:true,job};try{const result=await post(job);job.status="done";job.completedAt=new Date().toISOString();job.result=result;await KRDB.enqueue(job);updateStatus();return{queued:false,result,job}}catch(e){job.attempts++;job.lastError=String(e.message||e);await KRDB.enqueue(job);updateStatus();return{queued:true,error:e,job}}}
async function syncPending(){if(!apiUrl()||!navigator.onLine)return{sent:0,pending:(await KRDB.listQueue()).filter(x=>x.status!=="done").length};let sent=0;for(const job of (await KRDB.listQueue()).filter(x=>x.status!=="done").sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))){try{job.result=await post(job);job.status="done";job.completedAt=new Date().toISOString();job.lastError="";sent++}catch(e){job.attempts=(job.attempts||0)+1;job.lastError=String(e.message||e)}await KRDB.enqueue(job)}updateStatus();return{sent,pending:(await KRDB.listQueue()).filter(x=>x.status!=="done").length}}
async function getSnapshot(){if(!apiUrl())throw new Error("GREEN_API_NOT_CONFIGURED");try{const r=await requestBridge("snapshot",{},6000);return r}catch(e){const u=new URL(apiUrl());u.searchParams.set("action","snapshot");u.searchParams.set("_",Date.now());const r=await fetch(u.toString(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP_"+r.status);return await r.json()}}
async function test(){if(!apiUrl())return{ok:false,error:"未設定"};try{const result=await requestBridge("ping",{},4000);return{ok:true,result}}catch(e){try{const job={id:makeId("ping","system"),operation:"ping",entityId:"system",payload:{time:new Date().toISOString()}};return{ok:true,result:await fetchPost(job)}}catch(e2){return{ok:false,error:String(e2.message||e2)}}}}
async function updateStatus(){const el=document.getElementById("apiState");if(!el)return;const q=(await KRDB.listQueue()).filter(x=>x.status!=="done").length;if(!apiUrl())el.textContent="Green API未接続・端末キュー "+q+"件";else if(bridgeReady)el.textContent="Green APIライブ接続・同期待ち "+q+"件";else el.textContent="Green API設定済み・接続待ち "+q+"件";el.classList.toggle("connected",bridgeReady)}
window.KRAPI={apiUrl,setApiUrl,run,enqueue,syncPending,test,getSnapshot,requestBridge,updateStatus};
window.addEventListener("online",()=>syncPending());
window.addEventListener("DOMContentLoaded",()=>setTimeout(async()=>{if(apiUrl())initBridge();await updateStatus();const input=document.getElementById("apiUrlInput"),save=document.getElementById("saveApiUrl"),testBtn=document.getElementById("testApiUrl"),sync=document.getElementById("syncQueue"),result=document.getElementById("apiResult");if(input)input.value=apiUrl();if(save)save.onclick=async()=>{setApiUrl(input.value);result.textContent=apiUrl()?"URLを保存しました":"API設定を解除しました";await updateStatus()};if(testBtn)testBtn.onclick=async()=>{result.textContent="接続確認中…";const r=await test();result.textContent=r.ok?"接続できました":"接続できません："+r.error;await updateStatus()};if(sync)sync.onclick=async()=>{result.textContent="同期中…";const r=await syncPending();result.textContent="送信 "+r.sent+"件 / 残り "+r.pending+"件";await updateStatus()}},250));})();