(()=>{const K=window.KRN,services={purchase:"💰 買取",work:"🔧 工事",delivery:"🚚 配送",recycle:"♻️ リサイクル",estimate:"📋 見積",sale:"🛒 販売"};let draft=null,timer=null,postalTimer=null,lastPostalLookup="",masters={work:[],recycle:[],transport:[]},staticModelMaster=[],mastersReady=false;async function loadMasters(){if(mastersReady)return;try{const now=Date.now(),[masterRes,snapshotRes]=await Promise.all([fetch("./data/masters.json?_="+now,{cache:"no-store"}),fetch("./data/snapshot.json?_="+now,{cache:"no-store"})]),j=await masterRes.json(),snapshot=snapshotRes.ok?await snapshotRes.json():{};masters={work:j.work||[],recycle:j.recycle||[],transport:j.transport||[]};staticModelMaster=Array.isArray(snapshot.modelMaster)?snapshot.modelMaster:[]}catch{}mastersReady=true}
function id(seed){return"nextdraft-"+(seed?.caseId||seed?.serviceOrderId||crypto.randomUUID())}
function blank(seed){const items={purchase:[],work:[],delivery:[],recycle:[],estimate:[],sale:[]};if(seed?.recycleItems?.length)items.recycle=JSON.parse(JSON.stringify(seed.recycleItems));return{id:id(seed),caseId:seed?.caseId||"",appointmentId:seed?.appointmentId||"",sourceServiceOrderId:seed?.serviceOrderId||"",sourceNotes:seed?.notes||"",updatedAt:Date.now(),customer:{name:seed?.name||"",phone:seed?.phone||"",postalCode:seed?.postalCode||seed?.zip||"",address:seed?.address||"",email:seed?.email||""},selected:seed?.recycleItems?.length?["recycle"]:["purchase"],items}}
function fill(){K.$("#name").value=draft.customer.name||"";K.$("#phone").value=draft.customer.phone||"";K.$("#postalCode").value=draft.customer.postalCode||"";K.$("#address").value=draft.customer.address||"";K.$("#email").value=draft.customer.email||"";postalStatus("");render()}K.openSlip=async seed=>{await loadMasters();let d=blank(seed),old=await KRDB.getDraft(d.id);if(old)d=old;draft=d;draft.customer=draft.customer||{};fill();K.overlay("slip").classList.add("on");queue()};
function syncCustomer(){if(!draft)return;draft.customer={...draft.customer,name:K.$("#name").value,phone:K.$("#phone").value,postalCode:K.$("#postalCode").value,address:K.$("#address").value,email:K.$("#email").value};queue()}
["name","phone","postalCode","address","email"].forEach(x=>K.$("#"+x).addEventListener("input",syncCustomer));
function postalDigits(){return K.$("#postalCode").value.replace(/\D/g,"").slice(0,7)}
function postalStatus(message,type=""){const el=K.$("#postalLookupStatus");el.textContent=message;el.className=type}
async function lookupPostal(force=false){const zip=postalDigits();clearTimeout(postalTimer);if(zip.length!==7){lastPostalLookup="";postalStatus(zip?"郵便番号7桁で自動検索します":"");if(force)postalStatus("郵便番号を7桁で入力してください","error");return}if(!force&&zip===lastPostalLookup)return;lastPostalLookup=zip;postalStatus("住所を検索中…");const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),8000);try{const r=await fetch("https://zipcloud.ibsnet.co.jp/api/search?zipcode="+encodeURIComponent(zip),{signal:controller.signal});if(!r.ok)throw new Error("HTTP "+r.status);const data=await r.json(),row=data?.results?.[0];if(!row){lastPostalLookup="";postalStatus("住所が見つかりません。手入力もできます","error");return}K.$("#postalCode").value=zip.slice(0,3)+"-"+zip.slice(3);K.$("#address").value=[row.address1,row.address2,row.address3].filter(Boolean).join("");syncCustomer();postalStatus("✓ 住所を自動入力しました","success")}catch(error){lastPostalLookup="";postalStatus(error?.name==="AbortError"?"住所検索がタイムアウトしました":"住所検索に失敗しました。手入力はできます","error")}finally{clearTimeout(timeout)}}
K.$("#postalCode").addEventListener("input",()=>{clearTimeout(postalTimer);postalTimer=setTimeout(()=>lookupPostal(false),450)});K.$("#postalCode").addEventListener("blur",()=>{const zip=postalDigits();if(zip.length===7)K.$("#postalCode").value=zip.slice(0,3)+"-"+zip.slice(3)});K.$("#lookupPostalCode").onclick=()=>lookupPostal(true);
function queue(){clearTimeout(timer);K.$("#saveState").textContent="端末へ保存中…";timer=setTimeout(save,400)}async function save(){if(!draft)return;draft.updatedAt=Date.now();await KRDB.putDraft(draft);K.$("#saveState").textContent="✓ IndexedDBに自動保存済み";K.refreshResume()}K.$("#saveDraft").onclick=save;const categoryOrder=["エアコン","冷蔵庫","洗濯機","TV","電子レンジ","食洗機","その他家電"];const airconMakerOrder=[{label:"ダイキン",keys:["DAIKIN","ダイキン"]},{label:"パナソニック",keys:["PANASONIC","パナソニック"]},{label:"日立",keys:["HITACHI","日立"]},{label:"三菱電機",keys:["MITSUBISHI","三菱電機"]},{label:"シャープ",keys:["SHARP","シャープ"]},{label:"東芝",keys:["TOSHIBA","東芝"]},{label:"富士通ゼネラル",keys:["FUJITSU","富士通ゼネラル","富士通"]},{label:"アイリスオーヤマ",keys:["IRIS OHYAMA","アイリスオーヤマ"]},{label:"コロナ",keys:["CORONA","コロナ"]},{label:"三菱重工",keys:["MITSUBISHI HEAVY","三菱重工"]},{label:"ハイセンス",keys:["HISENSE","ハイセンス"]},{label:"ハイアール",keys:["HAIER","ハイアール"]},{label:"Midea",keys:["MIDEA","美的","ミデア"]},{label:"LG",keys:["LG","LG ELECTRONICS"]}];const makerPriorityByCategory={"冷蔵庫":[["パナソニック",["PANASONIC","パナソニック"]],["日立",["HITACHI","日立"]],["三菱電機",["MITSUBISHI","三菱電機"]],["東芝",["TOSHIBA","東芝"]],["シャープ",["SHARP","シャープ"]],["AQUA",["AQUA","アクア"]],["ハイアール",["HAIER","ハイアール"]],["ハイセンス",["HISENSE","ハイセンス"]],["LG",["LG","LG ELECTRONICS"]],["Midea",["MIDEA","美的","ミデア"]]],"洗濯機":[["パナソニック",["PANASONIC","パナソニック"]],["日立",["HITACHI","日立"]],["東芝",["TOSHIBA","東芝"]],["シャープ",["SHARP","シャープ"]],["AQUA",["AQUA","アクア"]],["ハイアール",["HAIER","ハイアール"]],["ハイセンス",["HISENSE","ハイセンス"]],["LG",["LG","LG ELECTRONICS"]],["Midea",["MIDEA","美的","ミデア"]]],"TV":[["SONY",["SONY","ソニー"]],["REGZA",["REGZA","TOSHIBA","レグザ","東芝"]],["シャープ",["SHARP","シャープ"]],["パナソニック",["PANASONIC","パナソニック"]],["ハイセンス",["HISENSE","ハイセンス"]],["TCL",["TCL"]],["LG",["LG","LG ELECTRONICS"]],["FUNAI",["FUNAI","フナイ"]],["MAXZEN",["MAXZEN","マクスゼン"]]],"電子レンジ":[["パナソニック",["PANASONIC","パナソニック"]],["シャープ",["SHARP","シャープ"]],["東芝",["TOSHIBA","東芝"]],["日立",["HITACHI","日立"]],["ハイアール",["HAIER","ハイアール"]],["ハイセンス",["HISENSE","ハイセンス"]],["AQUA",["AQUA","アクア"]],["Midea",["MIDEA","美的","ミデア"]],["アイリスオーヤマ",["IRIS OHYAMA","アイリスオーヤマ"]],["山善",["YAMAZEN","山善"]]]};
function catKey(v){const n=K.norm(v);return n==="テレビ"||n==="TV"?"TV":n}
function sameCategory(a,b){return!b||catKey(a)===catKey(b)}
function makerKey(v){const n=K.norm(v);for(const x of airconMakerOrder){if(x.keys.some(k=>n.includes(K.norm(k))))return K.norm(x.label)}return n}
function sameMaker(a,b){if(!b)return true;const aa=makerKey(a),bb=makerKey(b);return aa===bb||aa.startsWith(bb)||bb.startsWith(aa)}
const modelHistoryKey="kr-next-model-history-v1";
function modelHistory(){try{return JSON.parse(localStorage.getItem(modelHistoryKey)||"[]")}catch{return[]}}
function modelMasterRows(){const map=new Map();for(const x of staticModelMaster.concat(K.snap.modelMaster||[])){const key=compactModel(x.model)+"|"+makerKey(x.maker);if(key&&!map.has(key))map.set(key,x)}return[...map.values()]}
function rememberModel(category,maker,model,year){if(!model)return;const next=[{category,maker,model,yearMax:year||"",usageCount:999,quality:"recent-local",lastUsedAt:Date.now()},...modelHistory().filter(x=>compactModel(x.model)!==compactModel(model)||makerKey(x.maker)!==makerKey(maker))].slice(0,80);localStorage.setItem(modelHistoryKey,JSON.stringify(next))}
function categoryCandidates(q=""){const nq=K.norm(q),seen=new Set(),out=[];for(const x of categoryOrder){if(!nq||K.norm(x).includes(nq)){seen.add(catKey(x));out.push(x)}}for(const x of modelMasterRows()){const v=String(x.category||"").trim(),k=catKey(v);if(v&&!seen.has(k)&&(!nq||K.norm(v).includes(nq))){seen.add(k);out.push(v)}}return out}
function makerCandidates(cat,q=""){const nq=K.norm(q),ck=catKey(cat);if(ck===K.norm("エアコン"))return airconMakerOrder.filter(x=>!nq||K.norm(x.label+" "+x.keys.join(" ")).includes(nq)).map((x,i)=>({label:x.label,value:x.label,meta:i<10?(i+1)+"位":"海外"}));const map=new Map();for(const x of modelMasterRows()){if(!sameCategory(x.category,cat))continue;const m=String(x.maker||"").trim();if(!m||m==="要確認"||m==="未使用")continue;if(nq&&!K.norm(m).includes(nq))continue;map.set(m,(map.get(m)||0)+Number(x.usageCount||1))}const priority=makerPriorityByCategory[ck]||[];const out=[],seen=new Set();for(const [label,keys] of priority){if(nq&&!K.norm(label+" "+keys.join(" ")).includes(nq))continue;out.push({label,value:label,meta:"候補"});seen.add(makerKey(label))}for(const [label,count] of [...map.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],"ja"))){if(seen.has(makerKey(label)))continue;out.push({label,value:label,meta:"使用 "+count});seen.add(makerKey(label));if(out.length>=40)break}return out.slice(0,40)}
function modelQueryMatches(value,q){if(!q)return true;const plain=K.norm(value),nq=K.norm(q),modelCode=compactModel(value),queryCode=compactModel(q);if(plain.includes(nq)||modelCode.includes(queryCode))return true;if(queryCode.length<4)return false;const head=modelCode.slice(0,Math.min(modelCode.length,queryCode.length));return editDistance(head,queryCode)<=1}
function modelMatches(cat,maker,q,limit=60){const seen=new Set(),out=[],all=modelHistory().concat(modelMasterRows());let rows=all.filter(x=>sameCategory(x.category,cat)&&sameMaker(x.maker,maker)&&modelQueryMatches(x.model,q));if(!rows.length&&q)rows=all.filter(x=>modelQueryMatches(x.model,q));rows.sort((a,b)=>(b.quality==="recent-local")-(a.quality==="recent-local")||(b.quality==="verified-by-use")-(a.quality==="verified-by-use")||Number(b.usageCount)-Number(a.usageCount)||String(a.model).localeCompare(String(b.model)));for(const x of rows){const key=compactModel(x.model)+"|"+makerKey(x.maker);if(!key||seen.has(key))continue;seen.add(key);out.push(x);if(out.length>=limit)break}return out}
function render(){const sb=K.$("#serviceButtons");sb.innerHTML="";Object.entries(services).forEach(([key,label])=>{const b=document.createElement("button");b.textContent=label;b.classList.toggle("active",draft.selected.includes(key));b.onclick=()=>{if(draft.selected.includes(key)&&draft.selected.length>1)draft.selected=draft.selected.filter(x=>x!==key);else if(!draft.selected.includes(key))draft.selected.push(key);render();queue()};sb.appendChild(b)});const area=K.$("#serviceArea");area.innerHTML="";draft.selected.forEach(key=>{const p=document.createElement("section");p.className="servicePanel";const rows=draft.items[key]||[];p.innerHTML="<h3>"+services[key]+"</h3>"+(rows.map((x,i)=>'<div class="item slipLineItem"><div class="itemMain"><b>'+K.esc([x.category,x.maker,x.model].filter(Boolean).join(" / "))+'</b><span>'+K.esc([x.year,x.spec].filter(Boolean).join(" / "))+'</span></div><div class="itemSide"><b>¥'+Number(x.amount||0).toLocaleString()+'</b><button type="button" class="itemDelete" data-i="'+i+'" aria-label="明細を削除">×</button></div></div>').join("")||'<div class="empty">明細はまだありません</div>')+'<button class="add">＋ 明細を追加</button><div class="host"></div>';p.querySelectorAll(".itemDelete").forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.i);if(!Number.isInteger(i)||i<0||i>=draft.items[key].length)return;if(confirm("この明細を削除しますか？")){draft.items[key].splice(i,1);render();queue()}});p.querySelector(".add").onclick=()=>editor(p.querySelector(".host"),key);area.appendChild(p)});calc()}
function editor(host,key){if(key==="work"&&masters.work.length)return workEditor(host,key);if(key==="recycle"&&masters.recycle.length)return recycleEditor(host,key);genericEditor(host,key)}

let ocrLibraryPromise=null,ocrWorkerPromise=null,ocrProgressHandler=()=>{};
function loadOcrLibrary(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(ocrLibraryPromise)return ocrLibraryPromise;ocrLibraryPromise=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";script.crossOrigin="anonymous";script.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error("OCR_LIBRARY_UNAVAILABLE"));script.onerror=()=>reject(new Error("OCR_LIBRARY_LOAD_FAILED"));document.head.appendChild(script)});return ocrLibraryPromise}
async function ocrWorker(onProgress){ocrProgressHandler=typeof onProgress==="function"?onProgress:()=>{};const T=await loadOcrLibrary();if(!ocrWorkerPromise)ocrWorkerPromise=T.createWorker("eng+jpn",1,{logger:m=>{if(m.status==="recognizing text")ocrProgressHandler(Math.round(Number(m.progress||0)*100))}}).then(async worker=>{await worker.setParameters({tessedit_pageseg_mode:"11",preserve_interword_spaces:"1"});return worker});return ocrWorkerPromise}
async function recognizeOcrPass(worker,canvas,pageSegMode,modelOnly=false){await worker.setParameters({tessedit_pageseg_mode:String(pageSegMode),tessedit_char_whitelist:modelOnly?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_/.":""});return worker.recognize(canvas)}
async function ocrCanvas(file){let source=null,url="";try{if("createImageBitmap" in window)source=await createImageBitmap(file);else{url=URL.createObjectURL(file);source=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}const width=source.width||source.naturalWidth,height=source.height||source.naturalHeight,scale=Math.min(1,1800/Math.max(width,height)),w=Math.max(1,Math.round(width*scale)),h=Math.max(1,Math.round(height*scale)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h*2+8;const ctx=canvas.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0,w,h);ctx.drawImage(source,0,h+8,w,h);const image=ctx.getImageData(0,h+8,w,h),d=image.data;for(let i=0;i<d.length;i+=4){const gray=d[i]*.299+d[i+1]*.587+d[i+2]*.114,v=gray<155?Math.max(0,(gray-28)*1.35):Math.min(255,(gray+18)*1.22);d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(image,0,h+8);return canvas}finally{if(source&&typeof source.close==="function")source.close();if(url)URL.revokeObjectURL(url)}}
function compactModel(value){return String(value||"").normalize("NFKC").toUpperCase().replace(/[^A-Z0-9]/g,"")}
function editDistance(a,b){const prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let left=i,diag=i-1;for(let j=1;j<=b.length;j++){const up=prev[j],value=Math.min(up+1,left+1,diag+(a[i-1]===b[j-1]?0:1));diag=up;prev[j]=value;left=value}}return prev[b.length]}
function ocrModelCandidates(text,catValue,makerValue){const normalized=String(text||"").normalize("NFKC").toUpperCase(),compact=compactModel(normalized),tokens=(normalized.match(/[A-Z0-9][A-Z0-9._\/-]{3,24}/g)||[]).map(x=>x.replace(/^[._\/-]+|[._\/-]+$/g,"")).filter(x=>/[A-Z]/.test(x)&&/\d/.test(x)&&!/^(?:AC|DC)?\d+(?:V|W|HZ|KG|L)$/.test(x)&&!/^[0-9./-]+$/.test(x)),tokenCompacts=tokens.map(compactModel);const all=modelHistory().concat(modelMasterRows()),strict=all.filter(x=>sameCategory(x.category,catValue)&&sameMaker(x.maker,makerValue)),pool=strict.length?strict:all,known=pool.map(x=>{const code=compactModel(x.model);let score=compact.includes(code)?100:0;for(const token of tokenCompacts){const distance=editDistance(code,token),allowed=code.length>=9?2:1;if(distance<=allowed)score=Math.max(score,88-distance*8);if(token.includes(code)||code.includes(token))score=Math.max(score,82)}if(x.quality==="recent-local")score+=6;return{value:String(x.model),known:x,score}}).filter(x=>compactModel(x.value).length>=4&&x.score>0).sort((a,b)=>b.score-a.score);const raw=tokens.sort((a,b)=>(/[-/]/.test(b)?2:0)-(/[-/]/.test(a)?2:0)+Math.min(b.length,16)-Math.min(a.length,16)).map(value=>({value,known:null,score:40}));const seen=new Set(),out=[];for(const row of known.concat(raw)){const key=compactModel(row.value);if(key.length<4||seen.has(key))continue;seen.add(key);out.push(row);if(out.length>=6)break}return out}
function labelYear(text){const value=String(text||"").normalize("NFKC").toUpperCase(),patterns=[/(?:製造年|製造|年式|MFG(?:\.?\s*DATE)?|MANUFACTURED|PRODUCTION\s*DATE|DATE)[^0-9]{0,10}((?:19|20)\d{2})/,/((?:19|20)\d{2})\s*(?:年製|年|MODEL\s*YEAR)/];for(const pattern of patterns){const m=value.match(pattern),n=Number(m?.[1]);if(n>=1990&&n<=new Date().getFullYear()+1)return String(n)}return""}
function labelCategory(text){const value=String(text||"").normalize("NFKC").toUpperCase(),defs=[["エアコン",/ROOM\s*AIR\s*CONDITIONER|AIR\s*CONDITIONER|ルームエアコン|エアコン/],["冷蔵庫",/REFRIGERATOR|FREEZER|電気冷蔵庫|冷蔵庫/],["洗濯機",/WASHING\s*MACHINE|WASHER|洗濯乾燥機|全自動電気洗濯機|洗濯機/],["TV",/TELEVISION|LIQUID\s*CRYSTAL\s*TV|液晶テレビ|有機ELテレビ/],["電子レンジ",/MICROWAVE(?:\s*OVEN)?|電子レンジ|オーブンレンジ/],["食洗機",/DISHWASHER|食器洗い乾燥機|食洗機/]];return defs.find(([,pattern])=>pattern.test(value))?.[0]||""}
function labelMaker(text){const value=String(text||"").normalize("NFKC").toUpperCase(),aliases=[];for(const x of airconMakerOrder)for(const key of [x.label,...x.keys])aliases.push([key,x.label]);for(const rows of Object.values(makerPriorityByCategory))for(const [label,keys] of rows)for(const key of [label,...keys])aliases.push([key,label]);for(const x of modelMasterRows())if(x.maker)aliases.push([x.maker,x.maker]);aliases.sort((a,b)=>String(b[0]).length-String(a[0]).length);const seen=new Set();for(const [key,label] of aliases){const normalized=String(key||"").normalize("NFKC").toUpperCase();if(normalized.length<2||seen.has(normalized))continue;seen.add(normalized);if(value.includes(normalized))return label}return""}
function labelData(row,text){return{category:String(row.known?.category||labelCategory(text)||""),maker:String(row.known?.maker||labelMaker(text)||""),year:labelYear(text),model:String(row.value||""),verified:Boolean(row.known&&row.score>=82)}}
async function recognizeModel(file,ui){const {cat,maker,model,year,status,candidates}=ui;status.className="ocrStatus";status.textContent="品目・メーカー・年式・型番を端末内で読み取り中…";candidates.classList.remove("open");candidates.innerHTML="";try{if(!file||!String(file.type||"").startsWith("image/"))throw new Error("IMAGE_REQUIRED");const canvas=await ocrCanvas(file),worker=await ocrWorker(progress=>{status.textContent="ラベルの4項目を読み取り中… "+progress+"%"});let result=await recognizeOcrPass(worker,canvas,11),text=result?.data?.text||"",rows=ocrModelCandidates(text,cat.value,maker.value);if(!rows.some(x=>x.known&&x.score>=82)){status.textContent="確実な型番一致がないため、文字を強調して再解析中…";result=await recognizeOcrPass(worker,canvas,6,true);text+="\n"+(result?.data?.text||"");rows=ocrModelCandidates(text,cat.value,maker.value)}if(!rows.length){status.className="ocrStatus error";status.textContent="4項目を確実に読み取れません。型番・製造年・メーカーが一枚に入るようラベルだけを大きく撮り直してください";return}const apply=row=>{const data=labelData(row,text);if(data.category)cat.value=data.category;if(data.maker)maker.value=data.maker;if(data.year)year.value=data.year;if(data.model)model.value=data.model;model.dispatchEvent(new Event("input",{bubbles:true}));const missing=[!data.category?"品目":"",!data.maker?"メーカー":"",!data.year?"年式":"",!data.model?"型番":""].filter(Boolean);status.className="ocrStatus"+(missing.length?" warning":"");status.textContent=missing.length?"自動反映しました。"+missing.join("・")+"はラベルで確認して手入力してください":"✓ 4項目を自動反映しました。登録前にラベルと一致するか確認してください"};const trusted=rows.find(row=>labelData(row,text).verified);if(trusted)apply(trusted);else{status.className="ocrStatus warning";status.textContent="誤登録防止のため自動確定していません。下の候補をラベルと照合して選んでください"}candidates.innerHTML="<small>読み取り候補（品目 / メーカー / 年式 / 型番）</small>";rows.forEach(row=>{const data=labelData(row,text),button=document.createElement("button");button.type="button";button.innerHTML="<b>"+K.esc(data.model)+"</b><span>"+K.esc([data.category||"品目未確認",data.maker||"メーカー未確認",data.year?data.year+"年":"年式未確認"].join(" / "))+"</span>";button.onclick=()=>apply(row);candidates.appendChild(button)});if(rows.length>1||!trusted)candidates.classList.add("open")}catch(error){status.className="ocrStatus error";status.textContent="ラベル読み取りを開始できません。通信を確認するか、4項目を手入力して候補から選んでください"}}
function genericEditor(host,key){const camera=key==="purchase",cameraHtml=camera?'<button type="button" class="scanModel" aria-label="カメラで品目・メーカー・年式・型番を読み取る">📷</button><input class="modelPhoto" type="file" accept="image/*" capture="environment" hidden>':"";host.innerHTML='<div class="editor productEditor"><label class="productField">品目<input class="cat" autocomplete="off" placeholder="タップして選択 / 手入力"></label><div class="suggestionPanel categorySuggestions"></div><label class="productField">メーカー<input class="maker" autocomplete="off" placeholder="タップして選択 / 手入力"></label><div class="suggestionPanel makerSuggestions"></div><label class="productField">型番</label><div class="modelInputRow '+(camera?'':'noCamera')+'"><input class="model" autocomplete="off" placeholder="2〜3文字で過去の候補を表示">'+cameraHtml+'</div><div class="suggestionPanel modelSuggestions scrollSuggestions"></div><div class="modelAssistRow"><span class="ocrStatus">'+(camera?'📷 でラベルの4項目を自動読取':'入力すると過去の型番候補を表示')+'</span></div><div class="ocrCandidates"></div>'+(camera?'<button type="button" class="confirmOcr hidden">✓ ラベルと一致・4項目を確定</button>':'')+'<div class="row"><input class="year" inputmode="numeric" placeholder="年式"><input class="amount" inputmode="numeric" placeholder="金額"></div><input class="spec" placeholder="仕様・メモ"><button class="save">追加</button></div>';const cat=host.querySelector(".cat"),maker=host.querySelector(".maker"),model=host.querySelector(".model"),year=host.querySelector(".year"),amount=host.querySelector(".amount"),spec=host.querySelector(".spec"),catBox=host.querySelector(".categorySuggestions"),makerBox=host.querySelector(".makerSuggestions"),modelBox=host.querySelector(".modelSuggestions"),scanModel=host.querySelector(".scanModel"),modelPhoto=host.querySelector(".modelPhoto"),ocrStatus=host.querySelector(".ocrStatus"),ocrCandidates=host.querySelector(".ocrCandidates"),confirmOcr=host.querySelector(".confirmOcr"),saveBtn=host.querySelector(".save");const boxes=[catBox,makerBox,modelBox];let ocrPending=false;function fourMissing(){return[[cat,"品目"],[maker,"メーカー"],[year,"年式"],[model,"型番"]].filter(([input])=>!input.value.trim()).map(([,label])=>label)}function markOcrPending(){ocrPending=true;if(confirmOcr)confirmOcr.classList.remove("hidden");saveBtn.disabled=true;ocrStatus.className="ocrStatus warning";ocrStatus.textContent="自動反映結果をラベルと照合し、「4項目を確定」を押してください"}
function closeExcept(box){boxes.forEach(x=>x.classList.toggle("open",x===box))}
function closeAll(){boxes.forEach(x=>x.classList.remove("open"))}
function showCategories(){const a=categoryCandidates(cat.value);catBox.innerHTML=a.map((x,i)=>'<button type="button" data-i="'+i+'"><b>'+K.esc(x)+'</b></button>').join("");closeExcept(catBox);[...catBox.children].forEach(b=>b.onclick=()=>{const next=a[+b.dataset.i];const changed=cat.value!==next;cat.value=next;if(changed){maker.value="";model.value="";year.value=""}catBox.classList.remove("open");showMakers()})}
function showMakers(){const a=makerCandidates(cat.value,maker.value);makerBox.innerHTML=a.length?a.map((x,i)=>'<button type="button" data-i="'+i+'"><b>'+K.esc(x.label)+'</b><span>'+K.esc(x.meta||"")+'</span></button>').join(""):'<div class="suggestionEmpty">候補なし・そのまま手入力できます</div>';closeExcept(makerBox);[...makerBox.querySelectorAll("button")].forEach(b=>b.onclick=()=>{const x=a[+b.dataset.i];maker.value=x.value;model.value="";makerBox.classList.remove("open");showModels()})}
function showModels(){const a=modelMatches(cat.value,maker.value,model.value,80);modelBox.innerHTML=a.length?a.map((x,i)=>'<button type="button" data-i="'+i+'"><b>'+K.esc(x.model)+'</b><span>'+K.esc((x.quality==="recent-local"?"最近入力 / ":"")+x.maker+" / "+x.category+(x.yearMax?" / "+x.yearMax+"年":""))+'</span></button>').join(""):'<div class="suggestionEmpty">候補なし・型番は手入力できます</div>';closeExcept(modelBox);[...modelBox.querySelectorAll("button")].forEach(b=>b.onclick=()=>{const x=a[+b.dataset.i];cat.value=x.category;maker.value=x.maker;model.value=x.model;if(!year.value)year.value=x.yearMax||"";closeAll()})}cat.addEventListener("focus",showCategories);cat.addEventListener("click",showCategories);cat.addEventListener("input",showCategories);maker.addEventListener("focus",showMakers);maker.addEventListener("click",showMakers);maker.addEventListener("input",showMakers);model.addEventListener("focus",showModels);model.addEventListener("click",showModels);model.addEventListener("input",showModels);if(scanModel&&modelPhoto){scanModel.onclick=()=>modelPhoto.click();ocrCandidates.addEventListener("click",e=>{if(e.target.closest("button"))setTimeout(markOcrPending,0)});modelPhoto.onchange=async()=>{const before=[cat.value,maker.value,year.value,model.value].join("|");scanModel.disabled=true;try{await recognizeModel(modelPhoto.files?.[0],{cat,maker,model,year,status:ocrStatus,candidates:ocrCandidates});const after=[cat.value,maker.value,year.value,model.value].join("|");if(after!==before)markOcrPending()}finally{scanModel.disabled=false;modelPhoto.value=""}};confirmOcr.onclick=()=>{const missing=fourMissing();if(missing.length){ocrStatus.className="ocrStatus error";ocrStatus.textContent=missing.join("・")+"をラベルで確認して入力してください";return}ocrPending=false;confirmOcr.classList.add("hidden");saveBtn.disabled=false;ocrStatus.className="ocrStatus";ocrStatus.textContent="✓ ラベルとの一致を確認済み・明細に追加できます"}}[year,amount,spec].forEach(x=>x.addEventListener("focus",closeAll));saveBtn.onclick=()=>{const missing=key==="purchase"?fourMissing():[];if(missing.length){ocrStatus.className="ocrStatus error";ocrStatus.textContent=missing.join("・")+"は買取明細の必須項目です";return}if(ocrPending){ocrStatus.className="ocrStatus warning";ocrStatus.textContent="ラベルと一致するか確認し、先に「4項目を確定」を押してください";return}const item={category:cat.value.trim(),maker:maker.value.trim(),model:model.value.trim(),year:year.value.trim(),amount:+K.digits(amount.value),spec:spec.value.trim()};draft.items[key].push(item);rememberModel(item.category,item.maker,item.model,item.year);render();queue()}}
function workEditor(host,key){const active=masters.work.filter(x=>String(x["有効"]||"")==="有効");host.innerHTML='<div class="editor special"><select class="workPick">'+active.map((x,i)=>'<option value="'+i+'">'+K.esc(x["工事項目"])+'｜'+Number(x["料金"]||0).toLocaleString()+'円</option>').join("")+'</select><div class="row"><input class="qty" type="number" min="1" value="1"><input class="amount" inputmode="numeric"></div><input class="memo" placeholder="補足（任意）"><div class="pricePreview"></div><button class="save">工事を追加</button></div>';const pick=host.querySelector(".workPick"),qty=host.querySelector(".qty"),amount=host.querySelector(".amount"),preview=host.querySelector(".pricePreview");
function upd(){const x=active[+pick.value],q=Math.max(1,+qty.value||1),p=Number(x?.["料金"]||0);if(p>0)amount.value=p*q;else if(!amount.value)amount.value=0;preview.textContent=(x?.["単位"]||"")+" / "+(p?Number(p).toLocaleString()+"円":"要見積もり")+" × "+q}pick.onchange=upd;qty.oninput=upd;upd();host.querySelector(".save").onclick=()=>{const x=active[+pick.value],q=Math.max(1,+qty.value||1);draft.items[key].push({category:"エアコン工事",maker:"",model:x?.["工事項目"]||"",year:"",amount:+K.digits(amount.value),quantity:q,spec:[x?.["単位"],host.querySelector(".memo").value].filter(Boolean).join(" / "),workCode:x?.["工事項目"]||""});render();queue()}}
const sizeMap={aircon:[["room","ルームエアコン","10"],["window","窓用","10"],["one","片側のみ","10"]],fridge:[["s","170L以下","31"],["m","171〜400L","32"],["l","401L以上","32"]],washer:[["washer_s","5.9kg以下","40"],["washer_l","6.0kg以上","40"],["drum","ドラム式","40"],["dryer","衣類乾燥機","40"]],tv:[["flat_s","薄型15V型以下","51"],["flat_m","薄型16〜29V型","52"],["flat_l","薄型30V型以上","52"],["crt_s","ブラウン管15型以下","21"],["crt_m","ブラウン管16〜29型","22"],["crt_l","ブラウン管30型以上","22"]]};
function recycleEditor(host,key){host.innerHTML='<div class="editor special"><div class="row"><select class="rtype"><option value="aircon">エアコン</option><option value="tv">テレビ</option><option value="fridge">冷蔵庫</option><option value="washer">洗濯機</option></select><select class="rsize"></select></div><input class="rmaker" placeholder="メーカー名・コード"><div class="modelSuggestions makers"></div><select class="rmode"><option value="normal">配送・買取・持込</option><option value="dispose">処分のみ</option></select><div class="recyclePreview">メーカーを選択してください</div><button class="save" disabled>リサイクルを追加</button></div>';const type=host.querySelector(".rtype"),size=host.querySelector(".rsize"),maker=host.querySelector(".rmaker"),box=host.querySelector(".makers"),mode=host.querySelector(".rmode"),preview=host.querySelector(".recyclePreview"),saveBtn=host.querySelector(".save");let selected=null;
function sizes(){size.innerHTML=(sizeMap[type.value]||[]).map((x,i)=>'<option value="'+i+'">'+x[1]+'</option>').join("");selected=null;maker.value="";box.innerHTML="";calc()}
function item(){return(sizeMap[type.value]||[])[+size.value]||["","",""]}
function suggestions(){const code=item()[2],q=K.norm(maker.value);const rows=masters.recycle.filter(x=>x.itemCode===code&&(!q||K.norm(x.officialName+" "+x.aliases+" "+x.makerCode).includes(q))).slice(0,12);box.innerHTML=rows.map((x,i)=>'<button type="button" data-i="'+i+'"><b>'+K.esc(x.officialName)+'</b><span>コード '+K.esc(x.makerCode)+' / '+Number(x.recycleFee).toLocaleString()+'円</span></button>').join("");[...box.children].forEach(b=>b.onclick=()=>{selected=rows[+b.dataset.i];maker.value=selected.officialName;box.innerHTML="";calc()})}
function calc(){const it=item(),tr=masters.transport.find(x=>x.type===type.value&&x.sizeKey===it[0]);const rf=selected?Number(selected.recycleFee||0):0,tf=tr?Number(mode.value==="dispose"?tr.disposeFee:tr.normalFee):0,total=rf+tf;preview.innerHTML=selected?"リサイクル "+rf.toLocaleString()+"円 ＋ 運搬 "+tf.toLocaleString()+"円 ＝ <b>"+total.toLocaleString()+"円</b>":"メーカーを選択してください";saveBtn.disabled=!selected;saveBtn.dataset.total=String(total);saveBtn.dataset.transport=String(tf)}type.onchange=sizes;size.onchange=()=>{selected=null;maker.value="";calc()};maker.oninput=suggestions;mode.onchange=calc;sizes();saveBtn.onclick=()=>{if(!selected)return;const it=item(),tr=+saveBtn.dataset.transport||0,total=+saveBtn.dataset.total||0;draft.items[key].push({category:"家電リサイクル",maker:selected.officialName,model:it[1],year:"",amount:total,spec:"リサイクル "+Number(selected.recycleFee).toLocaleString()+"円 / 運搬 "+tr.toLocaleString()+"円",recycleMakerCode:selected.makerCode,recycleItemCode:it[2],recycleFee:Number(selected.recycleFee),transportFee:tr,mode:mode.value});render();queue()}}

function calc(){let total=0;for(const key of draft.selected)for(const x of draft.items[key])total+=(key==="purchase"?-1:1)*(+x.amount||0);K.$("#total").textContent="¥"+total.toLocaleString()}K.refreshResume=async()=>{const a=(await KRDB.listDrafts()).sort((x,y)=>y.updatedAt-x.updatedAt);K.$("#resume").disabled=!a.length;K.$("#draftSummary").textContent=a.length?(a[0].customer?.name||"未入力")+"｜NEXT伝票入力中":"保存中のNEXT伝票はありません";K.$("#resume").onclick=()=>{if(!a[0])return;draft=a[0];fill();K.overlay("slip").classList.add("on")}};

function draftTotal(){let total=0;for(const key of draft.selected)for(const x of draft.items[key])total+=(key==="purchase"?-1:1)*(+x.amount||0);return total}
function draftValidationIssues(){if(!draft)return["伝票がありません"];const issues=[];if(!String(draft.customer?.name||"").trim())issues.push("お客様のお名前");const itemCount=Object.values(draft.items||{}).reduce((sum,rows)=>sum+(Array.isArray(rows)?rows.length:0),0);if(!itemCount)issues.push("明細を1件以上");(draft.items?.purchase||[]).forEach((item,index)=>{const missing=[["category","品目"],["maker","メーカー"],["year","年式"],["model","型番"]].filter(([key])=>!String(item[key]||"").trim()).map(([,label])=>label);if(missing.length)issues.push("買取明細"+(index+1)+"の"+missing.join("・"))});return issues}
function stopForDraftIssues(){const issues=draftValidationIssues();if(!issues.length)return false;alert("お客様確認へ進む前に入力してください\n・"+issues.join("\n・"));return true}

function renderPreview(){let h='<div class="previewBlock"><h3>'+K.esc(draft.customer.name||"お客様")+' 様</h3><div>'+K.esc(draft.customer.postalCode?"〒"+draft.customer.postalCode:"")+'</div><div>'+K.esc(draft.customer.address||"")+'</div><div>'+K.esc(draft.customer.phone||"")+'</div></div>';for(const key of draft.selected){if(!draft.items[key].length)continue;h+='<div class="previewBlock"><h3>'+services[key]+'</h3>'+draft.items[key].map(x=>'<div class="previewLine"><span>'+K.esc([x.category,x.maker,x.model,x.year,x.spec].filter(Boolean).join(" / "))+'</span><b>¥'+Number(x.amount||0).toLocaleString()+'</b></div>').join("")+'</div>'}h+='<div class="previewBlock"><div class="previewLine"><span>差引合計</span><b>¥'+draftTotal().toLocaleString()+'</b></div></div>';K.$("#previewBody").innerHTML=h}
let sig={canvas:null,ctx:null,drawn:false,drawing:false,last:null};

function setupSignature(){const canvas=K.$("#signatureCanvas");if(!canvas)return;const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(150*dpr));const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);ctx.lineWidth=2;ctx.lineCap="round";ctx.lineJoin="round";ctx.strokeStyle="#24332e";sig={canvas,ctx,drawn:false,drawing:false,last:null};const point=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};canvas.onpointerdown=e=>{e.preventDefault();canvas.setPointerCapture?.(e.pointerId);sig.drawing=true;sig.last=point(e)};canvas.onpointermove=e=>{if(!sig.drawing)return;e.preventDefault();const p=point(e);ctx.beginPath();ctx.moveTo(sig.last.x,sig.last.y);ctx.lineTo(p.x,p.y);ctx.stroke();sig.last=p;sig.drawn=true};const end=e=>{if(!sig.drawing)return;e.preventDefault();sig.drawing=false;sig.last=null};canvas.onpointerup=end;canvas.onpointercancel=end;canvas.onpointerleave=end}

function clearSignature(){if(!sig.ctx||!sig.canvas)return;sig.ctx.clearRect(0,0,sig.canvas.width,sig.canvas.height);sig.drawn=false}
async function sha256(text){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function finalizeSnapshot(){
  if(!draft)return;
  if(stopForDraftIssues())return;
  if(draft.selected.includes("purchase")&&!sig.drawn){
    alert("買取を含むため、お客様サインを入力してください。");
    return;
  }
  await save();
  const previous=await KRDB.snapshotsFor(draft.id),version=(previous.at(-1)?.version||0)+1,confirmedAt=new Date().toISOString();
  const payload=JSON.parse(JSON.stringify(draft));
  const signatureDataUrl=sig.drawn?sig.canvas.toDataURL("image/png"):"";
  const hash=await sha256(JSON.stringify({payload,confirmedAt,version}));
  const snap={id:"snapshot-"+draft.id+"-v"+version,draftId:draft.id,caseId:draft.caseId||"",sourceServiceOrderId:draft.sourceServiceOrderId||"",version,confirmedAt,total:draftTotal(),payload,signatureDataUrl,hash,status:"local-confirmed"};
  await KRDB.putSnapshot(snap);
  let syncState=null;
  if(window.KRAPI)syncState=await KRAPI.run("finalize-slip",snap.id,snap);
  else await KRDB.enqueue({id:"sync-"+snap.id,operation:"finalize-slip",entityId:snap.id,payload:snap,status:"pending",attempts:0,createdAt:confirmedAt});
  await KRDB.deleteDraft(draft.id);

  const apiResult=syncState&&!syncState.queued?(syncState.result?.result||syncState.result||{}):null;
  const serviceOrderId=apiResult?.serviceOrderId||draft.sourceServiceOrderId||"";
  const blueSend=K.$("#bluePdfSend");
  blueSend.dataset.slip=serviceOrderId;
  blueSend.dataset.version=String(version);
  blueSend.dataset.email=String(draft.customer.email||"").trim();
  blueSend.dataset.resend="0";
  const canEmail=Boolean(apiResult&&serviceOrderId&&blueSend.dataset.email);
  blueSend.dataset.mode=canEmail?"email":"blue";
  blueSend.disabled=!serviceOrderId;
  blueSend.textContent=canEmail?"PDFをメール送信":(serviceOrderId?"顧客へ送信（現行Blue）":"顧客送信は伝票確定後");

  const hasPurchase=draft.selected.includes("purchase");
  if(draft.caseId&&K.updateLocalCase){
    await K.updateLocalCase(draft.caseId,{status:hasPurchase?"買取確定":"伝票確定",nextAction:hasPurchase?"在庫工程へ":"完了確認",updatedAt:confirmedAt});
  }
  if(draft.appointmentId){
    const appts=await KRDB.listAppointments().catch(()=>[]),a=appts.find(x=>String(x.appointmentId)===String(draft.appointmentId));
    if(a){
      a.status="completed";
      a.updatedAt=confirmedAt;
      if(serviceOrderId)a.serviceOrderId=serviceOrderId;
      await KRDB.putAppointment(a);
    }
  }
  K.renderCalendar&&K.renderCalendar();
  K.renderHome&&K.renderHome();
  K.$("#confirmedPanel").classList.remove("hidden");
  const generated=Array.isArray(apiResult?.inventory)?apiResult.inventory:[];
  const pdfUrl=String(apiResult?.pdfFileUrl||"");
  let statusHtml="<b>✓ お客様確認済み・第"+version+"版</b><span>"+new Date(confirmedAt).toLocaleString("ja-JP")+(apiResult?" / Green保存済み":" / Green共有同期待ち")+"</span>";
  statusHtml+='<div class="documentDeliveryStatus"><div><span>PDF</span><b>'+(apiResult?("第"+version+"版 発行済み"):"同期後に発行")+'</b></div><div><span>顧客送信</span><b class="unsent">未送信</b></div></div><div id="documentSendResult" class="documentSendResult" role="status"></div>';
  if(pdfUrl)statusHtml+='<a class="confirmedPdfLink" target="_blank" rel="noopener" href="'+K.esc(pdfUrl)+'">発行PDFを確認</a>';
  if(generated.length)statusHtml+='<div class="generatedInventoryLinks"><small>在庫を自動生成しました</small>'+generated.map((x,i)=>'<button type="button" data-inv="'+K.esc(x.inventoryId||"")+'" data-no="'+K.esc(x.inventoryNo||"")+'">'+K.esc(x.inventoryNo||("在庫"+(i+1)))+' を開く</button>').join("")+'</div>';
  K.$("#confirmedPanel").innerHTML=statusHtml;
  K.$$("#confirmedPanel .generatedInventoryLinks button").forEach(b=>b.onclick=async()=>{
    const id=b.dataset.inv,no=b.dataset.no;
    try{
      const live=await KRAPI.getSnapshot();
      if(live&&Array.isArray(live.inventory)){
        K.snap=live;
        const item=live.inventory.find(x=>x.inventoryId===id||x.inventoryNo===no);
        if(item){
          K.overlay("preview").classList.remove("on");
          K.overlay("slip").classList.remove("on");
          K.openInventoryDetail&&K.openInventoryDetail(item);
          return;
        }
      }
    }catch{}
    const u=new URL(location.href);
    u.searchParams.set("inventory",id||no);
    location.href=u.toString();
  });
  K.$("#previewStatus").textContent="第"+version+"版・端末確定済み";
  K.$("#finalizeConfirmation").disabled=true;
  K.$("#finalizeConfirmation").textContent="✓ 確定済み";
  await K.refreshResume();
}
K.$("#customerPreview").onclick=()=>{if(!draft||stopForDraftIssues())return;renderPreview();K.$("#confirmedPanel").classList.add("hidden");K.$("#previewStatus").textContent="内容をご確認ください";K.$("#finalizeConfirmation").disabled=false;K.$("#finalizeConfirmation").textContent="✓ 確認・署名を確定";const send=K.$("#bluePdfSend");send.disabled=true;send.textContent="顧客送信は伝票確定後";send.dataset.slip="";send.dataset.mode="";send.dataset.email="";send.dataset.version="";send.dataset.resend="0";K.overlay("preview").classList.add("on");requestAnimationFrame(setupSignature)};
K.$("#clearSignature").onclick=clearSignature;
K.$("#finalizeConfirmation").onclick=finalizeSnapshot;
K.$("#printPreview").onclick=()=>window.print();
K.$("#bluePdfSend").onclick=async()=>{
  const button=K.$("#bluePdfSend"),slip=button.dataset.slip||draft?.sourceServiceOrderId||"";
  if(button.dataset.mode!=="email"){
    K.overlay("preview").classList.remove("on");
    K.overlay("slip").classList.remove("on");
    slip?K.openBlue("slips",{slip}):K.openBlue("slips");
    return;
  }
  const email=button.dataset.email||"",version=button.dataset.version||"1",resend=button.dataset.resend==="1";
  if(!confirm("第"+version+"版PDFを "+email+" へ"+(resend?"再送":"送信")+"しますか？"))return;
  const resultEl=K.$("#documentSendResult");
  button.disabled=true;
  button.textContent=resend?"再送信中…":"送信中…";
  if(resultEl){resultEl.className="documentSendResult working";resultEl.textContent="宛先とPDFを確認しています…"}
  try{
    const raw=await KRAPI.runImmediate("send-slip-pdf-email",slip,{resend}),result=raw?.result||raw||{};
    const delivery=K.$("#confirmedPanel .documentDeliveryStatus .unsent");
    if(delivery){delivery.classList.remove("unsent");delivery.classList.add("sent");delivery.textContent="送信済み（メール）"}
    if(resultEl){resultEl.className="documentSendResult success";resultEl.textContent=result.message||("\u7b2c"+version+"\u7248PDF\u3092\u30e1\u30fc\u30eb\u3067\u9001\u4fe1\u3057\u307e\u3057\u305f\u3002")}
    button.dataset.resend="1";
    button.textContent="PDFをメール再送";
  }catch(error){
    if(resultEl){resultEl.className="documentSendResult error";resultEl.textContent="送信できません："+String(error?.message||error)}
    button.textContent=resend?"PDFをメール再送":"PDFをメール送信";
  }finally{
    button.disabled=false;
  }
};
})();
