import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../next/menu-workspace.js',import.meta.url),'utf8');
function setup(){const map=new Map(),calls=[];function el(){const c=new Set();return{scrollTop:0,classList:{contains:k=>c.has(k),add:k=>c.add(k),remove:k=>c.delete(k),toggle(k,on){on?c.add(k):c.delete(k)}},addEventListener(){}};}const $=s=>{if(!map.has(s))map.set(s,el());return map.get(s)};const K={$ ,overlay:id=>$('#'+id),screen:s=>calls.push('screen:'+s),setNav:()=>{},openTab:async t=>calls.push(t),slipWorkspace:{save:async()=>{},confirmed:false}};const ctx=vm.createContext({window:{KRN:K,scrollY:55,scrollTo:()=>{}},document:{body:el()},MutationObserver:class{observe(){}},alert:()=>{}});vm.runInContext(source,ctx);return{K,$,calls};}
test('assessment input panel restores without rerendering its unsent input DOM',async()=>{const{K,$,calls}=setup();$('#phoneAssessmentModal').classList.add('on');$('#phoneAssessmentModal > section').scrollTop=123;await K.openTab('inventory');assert.equal($('#phoneAssessmentModal').classList.contains('on'),false);await K.openTab('assessment');assert.equal($('#phoneAssessmentModal').classList.contains('on'),true);assert.equal($('#phoneAssessmentModal > section').scrollTop,123);assert.deepEqual(calls,['inventory','screen:assessmentView']);});
test('inventory detail and nested process panel both restore',async()=>{const{K,$}=setup();$('#inventoryDetailModal').classList.add('on');$('#processModal').classList.add('on');await K.openTab('schedule');await K.openTab('inventory');assert.equal($('#inventoryDetailModal').classList.contains('on'),true);assert.equal($('#processModal').classList.contains('on'),true);});
test('customer confirmation retains the same signature panel while changing menus',async()=>{const{K,$}=setup();$('#preview').classList.add('on');await K.openTab('schedule');assert.equal($('#preview').classList.contains('on'),false);await K.openTab('slips');assert.equal($('#preview').classList.contains('on'),true);});
test('explicitly closed detail is not reopened by the next menu round trip',async()=>{const{K,$}=setup();$('#inventoryDetailModal').classList.add('on');await K.openTab('assessment');await K.openTab('inventory');$('#inventoryDetailModal').classList.remove('on');await K.openTab('assessment');await K.openTab('inventory');assert.equal($('#inventoryDetailModal').classList.contains('on'),false);});
test('customer confirmation hides the menu and does not reserve a blank menu strip',()=>{const css=fs.readFileSync(new URL('../next/slip-workspace.css',import.meta.url),'utf8');assert.match(source,/const confirming=K.overlay\('preview'\).classList.contains\('on'\)/);assert.match(css,/body\.customerConfirming \.nav\{display:none!important\}/);assert.match(css,/#preview\{bottom:0!important/);assert.match(css,/#slip\{bottom:calc\(76px/);});
test('confirming a slip does not complete a future visit or an unconfirmed hold',()=>{const gas=fs.readFileSync(new URL('../next-green-gas/Code.gs',import.meta.url),'utf8');const ctx=vm.createContext({Utilities:{formatDate:()=> '2026-10-02'}});vm.runInContext(gas,ctx);assert.equal(ctx.slipAppointmentStatus_({date:'2026-10-05',status:'confirmed'},'2026-10-02T00:00:00Z'),'confirmed');assert.equal(ctx.slipAppointmentStatus_({date:'2026-10-02',status:'confirmed'},'2026-10-02T00:00:00Z'),'completed');assert.equal(ctx.slipAppointmentStatus_({date:'2026-10-02',status:'tentative'},'2026-10-02T00:00:00Z'),'tentative');});
