import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
test('unchanged slips bypass the prompt and timestamps do not count as changes',()=>{const source=fs.readFileSync(new URL('../next/slip-controls.js',import.meta.url),'utf8');const from=source.indexOf('const content='),to=source.indexOf("K.$('#slip')",from);const ctx=vm.createContext({openedContent:'',focusedValues:new Map(),w:{current:()=>({customer:{name:'test'},updatedAt:1})}});vm.runInContext(source.slice(from,to)+';captureContent();globalThis.compare=content;',ctx);assert.equal(ctx.openedContent,ctx.compare({customer:{name:'test'},updatedAt:2}));assert.notEqual(ctx.openedContent,ctx.compare({customer:{name:'changed'},updatedAt:2}));assert.match(source,/if\(!changed\(\)\)return Promise.resolve\('save'\)/);});
test('draft delete is concealed until horizontal reveal and vertical scrolling is retained',()=>{const source=fs.readFileSync(new URL('../next/slip-controls.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../next/slip-workspace.css',import.meta.url),'utf8');assert.match(source,/Math.abs\(dx\)>Math.abs\(dy\)\*1.5/);assert.match(source,/button.tabIndex=-1/);assert.match(css,/touch-action:pan-y/);assert.match(css,/font-size:16px!important/);});
const slip=fs.readFileSync(new URL('../next/slip.js',import.meta.url),'utf8'),controls=fs.readFileSync(new URL('../next/slip-controls.js',import.meta.url),'utf8'),workspace=fs.readFileSync(new URL('../next/slip-workspace.js',import.meta.url),'utf8'),gas=fs.readFileSync(new URL('../next-green-gas/Code.gs',import.meta.url),'utf8');
test('back can cancel, save, or discard; cancelling does not close the input',async()=>{for(const choice of ['cancel','save','discard']){const calls=[];const K={requestSlipExit:async()=>choice,slipWorkspace:{confirmed:false,discardOnExit:async()=>calls.push('discard'),onClosed:()=>{}},overlay:()=>({classList:{remove:()=>calls.push('close')}}),$:()=>({}),forgetWorkspace:()=>{},renderLocalSlips:()=>{}};const ctx=vm.createContext({K,timer:null,clearTimeout:()=>{},save:async()=>calls.push('save')});const from=slip.indexOf('async function closeSlipSafely()'),to=slip.indexOf('["closeSlip"',from);vm.runInContext(slip.slice(from,to),ctx);await ctx.closeSlipSafely();assert.deepEqual(calls,choice==='cancel'?[]:[choice==='discard'?'discard':'save','close']);}});
test('discard restores the original saved draft, while a new unwanted draft is removed',async()=>{for(const baseline of [null,{id:'draft-1',customer:{name:'original'}}]){const calls=[];const ctx=vm.createContext({baseline,w:{current:()=>({id:'draft-1'}),clear:()=>calls.push('clear')},KRDB:{putDraft:async d=>calls.push(d),deleteDraft:async id=>calls.push(id)},K:{refreshResume:async()=>{}}});const start=controls.indexOf('w.discardOnExit='),end=controls.indexOf('const text=',start);vm.runInContext(controls.slice(start,end),ctx);await ctx.w.discardOnExit();assert.equal(calls[0],'clear');assert.deepEqual(calls[1],baseline||'draft-1');}});
test('shared archive is reversible and does not delete PDF, inventory or appointments',()=>{const ctx=vm.createContext({});vm.runInContext(gas,ctx);const props=new Map();ctx.PropertiesService={getScriptProperties:()=>({getProperty:key=>props.get(key),setProperty:(key,value)=>props.set(key,value)})};ctx.findRow_=()=>2;ctx.audit_=()=>{};assert.deepEqual(Array.from(ctx.opServiceOrderArchive_('UT-TEST',{}).archivedServiceOrderIds),['UT-TEST']);assert.deepEqual(Array.from(ctx.opServiceOrderArchive_('UT-TEST',{archived:false}).archivedServiceOrderIds),[]);ctx.findRow_=()=>null;assert.throws(()=>ctx.opServiceOrderArchive_('UT-MISSING',{}),/見つかりません/);});
test('slot choices are bounded to half-hours and end choices follow the selected start',()=>{const ctx=vm.createContext({});const from=workspace.indexOf('const slots='),to=workspace.indexOf('function setSlots',from);vm.runInContext(workspace.slice(from,to)+';globalThis.result=slots;',ctx);const slots=Array.from(ctx.result);assert.equal(slots[0],'08:00');assert.equal(slots.at(-1),'20:00');assert.equal(slots.length,25);assert.deepEqual(slots.filter(t=>t>'09:00').slice(0,3),['09:30','10:00','10:30']);assert.match(workspace,/slots\.filter\(t=>!start\|\|t>start\)/);});
test('draft removal requires explicit confirmation and never cancels a visit',()=>{assert.match(controls,/async function removeDraft\(id\)\{if\(!confirm\(/);assert.doesNotMatch(controls,/appointment-delete|cancel-visit|DriveApp|deleteSnapshot/);});
